/**
 * Mock data for Opportunity Hub expansion features.
 * Structured for future FastAPI backend consumption — swap these
 * exports for real HTTP calls in opportunitiesApi without UI changes.
 */

import type {
  IndustrySector,
  SmartRecommendation,
  CareerPath,
  FeaturedEmployer,
  WeeklyInsights,
} from '@/lib/types';

export const INDUSTRY_SECTORS: IndustrySector[] = [
  {
    id: 'technology',
    name: 'Technology',
    emoji: '💻',
    icon: 'Laptop',
    description: 'Software, cloud, AI, cybersecurity, and digital products across Africa.',
    opportunityCount: 842,
    trending: true,
    trendPercent: 31,
    color: 'from-blue-500 to-blue-600',
  },
  {
    id: 'banking-fintech',
    name: 'Banking & FinTech',
    emoji: '🏦',
    icon: 'Landmark',
    description: 'Banks, payment platforms, lending, and financial infrastructure.',
    opportunityCount: 518,
    trending: true,
    trendPercent: 24,
    color: 'from-emerald-500 to-emerald-600',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    emoji: '🏥',
    icon: 'HeartPulse',
    description: 'Hospitals, healthtech, pharmaceuticals, and public health roles.',
    opportunityCount: 276,
    trending: true,
    trendPercent: 18,
    color: 'from-rose-500 to-rose-600',
  },
  {
    id: 'education',
    name: 'Education',
    emoji: '🎓',
    icon: 'GraduationCap',
    description: 'EdTech, universities, training academies, and learning platforms.',
    opportunityCount: 194,
    trending: false,
    trendPercent: 9,
    color: 'from-violet-500 to-violet-600',
  },
  {
    id: 'agriculture',
    name: 'Agriculture & Agritech',
    emoji: '🌾',
    icon: 'Wheat',
    description: 'Agribusiness, food systems, and climate-smart farming tech.',
    opportunityCount: 128,
    trending: true,
    trendPercent: 22,
    color: 'from-lime-500 to-lime-600',
  },
  {
    id: 'energy',
    name: 'Energy & Utilities',
    emoji: '⚡',
    icon: 'Zap',
    description: 'Oil & gas, renewables, power distribution, and utility tech.',
    opportunityCount: 167,
    trending: true,
    trendPercent: 15,
    color: 'from-amber-500 to-amber-600',
  },
  {
    id: 'logistics',
    name: 'Logistics & Transportation',
    emoji: '🚚',
    icon: 'Truck',
    description: 'Supply chain, last-mile delivery, freight, and mobility.',
    opportunityCount: 143,
    trending: false,
    trendPercent: 11,
    color: 'from-orange-500 to-orange-600',
  },
  {
    id: 'government',
    name: 'Government & Public Sector',
    emoji: '🏛',
    icon: 'Building2',
    description: 'Federal agencies, state roles, and public digital services.',
    opportunityCount: 98,
    trending: false,
    trendPercent: 6,
    color: 'from-slate-500 to-slate-600',
  },
  {
    id: 'legal',
    name: 'Legal Services',
    emoji: '⚖',
    icon: 'Scale',
    description: 'Law firms, compliance, legal tech, and corporate counsel.',
    opportunityCount: 72,
    trending: false,
    trendPercent: 4,
    color: 'from-indigo-500 to-indigo-600',
  },
  {
    id: 'media',
    name: 'Media & Communications',
    emoji: '📺',
    icon: 'Tv',
    description: 'Broadcast, digital media, PR, journalism, and content.',
    opportunityCount: 89,
    trending: false,
    trendPercent: 8,
    color: 'from-pink-500 to-pink-600',
  },
  {
    id: 'retail',
    name: 'Retail & E-commerce',
    emoji: '🛍',
    icon: 'ShoppingBag',
    description: 'Online marketplaces, retail ops, merchandising, and CX.',
    opportunityCount: 211,
    trending: true,
    trendPercent: 16,
    color: 'from-fuchsia-500 to-fuchsia-600',
  },
  {
    id: 'construction',
    name: 'Construction & Real Estate',
    emoji: '🏗',
    icon: 'HardHat',
    description: 'Property development, architecture support, and proptech.',
    opportunityCount: 104,
    trending: false,
    trendPercent: 7,
    color: 'from-stone-500 to-stone-600',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    emoji: '🏭',
    icon: 'Factory',
    description: 'Production, quality, industrial ops, and plant engineering.',
    opportunityCount: 91,
    trending: false,
    trendPercent: 5,
    color: 'from-zinc-500 to-zinc-600',
  },
  {
    id: 'aviation',
    name: 'Aviation',
    emoji: '✈',
    icon: 'Plane',
    description: 'Airlines, airport ops, aviation safety, and MRO roles.',
    opportunityCount: 47,
    trending: false,
    trendPercent: 3,
    color: 'from-sky-500 to-sky-600',
  },
  {
    id: 'hospitality',
    name: 'Hospitality & Tourism',
    emoji: '🏨',
    icon: 'Hotel',
    description: 'Hotels, travel tech, events, and tourism experiences.',
    opportunityCount: 86,
    trending: false,
    trendPercent: 10,
    color: 'from-teal-500 to-teal-600',
  },
  {
    id: 'sales-marketing',
    name: 'Sales & Marketing',
    emoji: '📈',
    icon: 'TrendingUp',
    description: 'Growth, digital marketing, sales enablement, and brand.',
    opportunityCount: 312,
    trending: true,
    trendPercent: 19,
    color: 'from-cyan-500 to-cyan-600',
  },
  {
    id: 'business-consulting',
    name: 'Business & Consulting',
    emoji: '📊',
    icon: 'Briefcase',
    description: 'Strategy, management consulting, ops, and advisory firms.',
    opportunityCount: 158,
    trending: false,
    trendPercent: 12,
    color: 'from-blue-600 to-indigo-600',
  },
  {
    id: 'creative-design',
    name: 'Creative & Design',
    emoji: '🎨',
    icon: 'Palette',
    description: 'UI/UX, brand design, motion, and creative production.',
    opportunityCount: 134,
    trending: true,
    trendPercent: 14,
    color: 'from-purple-500 to-purple-600',
  },
  {
    id: 'research',
    name: 'Research & Innovation',
    emoji: '🔬',
    icon: 'FlaskConical',
    description: 'Labs, R&D, policy research, and innovation hubs.',
    opportunityCount: 63,
    trending: false,
    trendPercent: 11,
    color: 'from-emerald-600 to-teal-600',
  },
  {
    id: 'nonprofit',
    name: 'Non-Profit & NGOs',
    emoji: '🤝',
    icon: 'Handshake',
    description: 'Development orgs, foundations, social impact, and advocacy.',
    opportunityCount: 117,
    trending: false,
    trendPercent: 8,
    color: 'from-green-500 to-green-600',
  },
];

export const ENHANCED_RECOMMENDATIONS: SmartRecommendation[] = [
  {
    id: 'rec_1',
    title: 'Backend Developer Internship',
    organization: 'Paystack',
    type: 'internship',
    confidence: 96,
    reasonKey: 'opportunityHub.recommendations.reasons.backend',
    reason: 'Strong match with your Node.js and API experience from your resume.',
    icon: 'Laptop',
    location: 'Lagos · Hybrid',
    salary: '₦150k – ₦250k',
    matchFactors: {
      resume: true,
      skills: ['Node.js', 'PostgreSQL', 'REST APIs'],
      careerGoal: 'Backend Engineering',
      education: "B.Sc Computer Science",
      experience: '1–2 years',
      preferredIndustry: 'Technology',
      preferredLocation: 'Lagos',
      language: 'en',
    },
    tags: ['Internship', 'FinTech'],
  },
  {
    id: 'rec_2',
    title: 'Google AI Essentials Course',
    organization: 'Google',
    type: 'learning',
    confidence: 91,
    reasonKey: 'opportunityHub.recommendations.reasons.aiCourse',
    reason: 'Closes a skill gap in AI identified from your career goal.',
    icon: 'BookOpen',
    location: 'Remote',
    matchFactors: {
      resume: true,
      skills: ['Python', 'Data Analysis'],
      careerGoal: 'AI / Machine Learning',
      education: "B.Sc Computer Science",
      experience: '1–2 years',
      preferredIndustry: 'Technology',
      preferredLocation: 'Remote',
      language: 'en',
    },
    tags: ['Free', 'AI'],
  },
  {
    id: 'rec_3',
    title: 'Africa Fintech Hackathon',
    organization: 'Devpost',
    type: 'hackathon',
    confidence: 87,
    reasonKey: 'opportunityHub.recommendations.reasons.hackathon',
    reason: 'Portfolio-building opportunity aligned with your fintech interest.',
    icon: 'Trophy',
    location: 'Online',
    matchFactors: {
      resume: true,
      skills: ['JavaScript', 'Python'],
      careerGoal: 'Backend Engineering',
      education: "B.Sc Computer Science",
      experience: '1–2 years',
      preferredIndustry: 'Banking & FinTech',
      preferredLocation: 'Remote',
      language: 'en',
    },
    tags: ['Hackathon', 'Prizes'],
  },
  {
    id: 'rec_4',
    title: '3MTT Community Mentorship Circle',
    organization: '3MTT Nigeria',
    type: 'networking',
    confidence: 84,
    reasonKey: 'opportunityHub.recommendations.reasons.community',
    reason: 'Matches your preferred location and community learning style.',
    icon: 'Users',
    location: 'Abuja · Hybrid',
    matchFactors: {
      resume: true,
      skills: ['Soft Skills', 'Networking'],
      careerGoal: 'Software Engineering',
      education: "B.Sc Computer Science",
      experience: 'Entry level',
      preferredIndustry: 'Technology',
      preferredLocation: 'Abuja',
      language: 'en',
    },
    tags: ['Community', 'Mentorship'],
  },
  {
    id: 'rec_5',
    title: 'Python Developer Scholarship',
    organization: 'Andela Learning Community',
    type: 'scholarship',
    confidence: 79,
    reasonKey: 'opportunityHub.recommendations.reasons.python',
    reason: 'Supports your goal to strengthen core programming fundamentals.',
    icon: 'GraduationCap',
    location: 'Remote · Africa',
    matchFactors: {
      resume: true,
      skills: ['Python'],
      careerGoal: 'Software Engineering',
      education: "B.Sc Computer Science",
      experience: 'Entry level',
      preferredIndustry: 'Technology',
      preferredLocation: 'Remote',
      language: 'en',
    },
    tags: ['Scholarship', 'Free'],
  },
  {
    id: 'rec_6',
    title: 'Junior Data Analyst',
    organization: 'Flutterwave',
    type: 'job',
    confidence: 88,
    reasonKey: 'opportunityHub.recommendations.reasons.backend',
    reason: 'Your SQL and analytics skills align with this role’s requirements.',
    icon: 'Briefcase',
    location: 'Lagos · On-site',
    salary: '₦8M – ₦12M',
    matchFactors: {
      resume: true,
      skills: ['SQL', 'Python', 'Excel'],
      careerGoal: 'Data Science',
      education: "B.Sc Computer Science",
      experience: '1–2 years',
      preferredIndustry: 'Banking & FinTech',
      preferredLocation: 'Lagos',
      language: 'en',
    },
    tags: ['Full-time', 'Data'],
  },
];

export const CAREER_PATHS: CareerPath[] = [
  {
    id: 'cp_software',
    title: 'Software Engineering',
    description: 'Design, build, and maintain software systems for products used by millions.',
    averageSalary: '₦6M – ₦25M',
    demand: 'very-high',
    growthTrend: 'exploding',
    growthPercent: 34,
    recommendedSkills: ['JavaScript', 'Python', 'System Design', 'Git', 'SQL'],
    recommendedCertifications: ['AWS Cloud Practitioner', 'Meta Frontend Certificate'],
    icon: 'Code2',
    color: 'from-blue-500 to-indigo-600',
    openRoles: 412,
  },
  {
    id: 'cp_ai',
    title: 'Artificial Intelligence',
    description: 'Build intelligent systems, ML models, and AI products for real-world impact.',
    averageSalary: '₦8M – ₦30M',
    demand: 'very-high',
    growthTrend: 'exploding',
    growthPercent: 48,
    recommendedSkills: ['Python', 'PyTorch', 'NLP', 'MLOps', 'Statistics'],
    recommendedCertifications: ['Google ML Engineer', 'DeepLearning.AI Specialization'],
    icon: 'Sparkles',
    color: 'from-violet-500 to-purple-600',
    openRoles: 98,
  },
  {
    id: 'cp_data',
    title: 'Data Science',
    description: 'Turn data into decisions with analysis, modelling, and storytelling.',
    averageSalary: '₦5M – ₦22M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 28,
    recommendedSkills: ['SQL', 'Python', 'Tableau', 'Statistics', 'A/B Testing'],
    recommendedCertifications: ['Google Data Analytics', 'IBM Data Science'],
    icon: 'BarChart3',
    color: 'from-cyan-500 to-blue-600',
    openRoles: 186,
  },
  {
    id: 'cp_cyber',
    title: 'Cybersecurity',
    description: 'Protect systems, data, and infrastructure from evolving threats.',
    averageSalary: '₦7M – ₦28M',
    demand: 'very-high',
    growthTrend: 'exploding',
    growthPercent: 41,
    recommendedSkills: ['Network Security', 'SIEM', 'Python', 'Compliance', 'Cloud Security'],
    recommendedCertifications: ['CompTIA Security+', 'CISSP', 'CEH'],
    icon: 'Shield',
    color: 'from-rose-500 to-red-600',
    openRoles: 74,
  },
  {
    id: 'cp_cloud',
    title: 'Cloud Engineering',
    description: 'Architect and operate scalable cloud infrastructure and platforms.',
    averageSalary: '₦8M – ₦26M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 32,
    recommendedSkills: ['AWS', 'Kubernetes', 'Terraform', 'Linux', 'CI/CD'],
    recommendedCertifications: ['AWS Solutions Architect', 'CKA', 'Azure Administrator'],
    icon: 'Cloud',
    color: 'from-sky-500 to-cyan-600',
    openRoles: 121,
  },
  {
    id: 'cp_pm',
    title: 'Product Management',
    description: 'Define product vision, prioritise roadmaps, and ship user value.',
    averageSalary: '₦7M – ₦24M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 22,
    recommendedSkills: ['Roadmapping', 'User Research', 'Analytics', 'Agile', 'Communication'],
    recommendedCertifications: ['Google PM Certificate', 'Product School'],
    icon: 'Target',
    color: 'from-amber-500 to-orange-600',
    openRoles: 89,
  },
  {
    id: 'cp_uiux',
    title: 'UI/UX Design',
    description: 'Craft delightful, accessible digital experiences for diverse users.',
    averageSalary: '₦4M – ₦18M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 19,
    recommendedSkills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Accessibility'],
    recommendedCertifications: ['Google UX Design', 'NN/g UX Certification'],
    icon: 'Palette',
    color: 'from-pink-500 to-fuchsia-600',
    openRoles: 112,
  },
  {
    id: 'cp_accounting',
    title: 'Accounting',
    description: 'Manage financial reporting, audit, tax, and corporate finance.',
    averageSalary: '₦3M – ₦15M',
    demand: 'moderate',
    growthTrend: 'stable',
    growthPercent: 6,
    recommendedSkills: ['IFRS', 'Excel', 'QuickBooks', 'Tax', 'Financial Analysis'],
    recommendedCertifications: ['ICAN', 'ACCA', 'CFA Level 1'],
    icon: 'Calculator',
    color: 'from-emerald-500 to-green-600',
    openRoles: 156,
  },
  {
    id: 'cp_ba',
    title: 'Business Analysis',
    description: 'Bridge business needs and technology solutions with clear requirements.',
    averageSalary: '₦4M – ₦16M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 17,
    recommendedSkills: ['Requirements', 'SQL', 'Process Mapping', 'Stakeholder Mgmt', 'Agile'],
    recommendedCertifications: ['CBAP', 'PMI-PBA', 'IIBA ECBA'],
    icon: 'LineChart',
    color: 'from-indigo-500 to-blue-600',
    openRoles: 94,
  },
  {
    id: 'cp_hr',
    title: 'Human Resources',
    description: 'Attract, develop, and retain talent across modern organisations.',
    averageSalary: '₦3.5M – ₦14M',
    demand: 'moderate',
    growthTrend: 'stable',
    growthPercent: 8,
    recommendedSkills: ['Recruiting', 'HRIS', 'Employee Relations', 'Compensation', 'L&D'],
    recommendedCertifications: ['CIPM', 'SHRM-CP', 'HRCI PHR'],
    icon: 'Users',
    color: 'from-teal-500 to-emerald-600',
    openRoles: 78,
  },
  {
    id: 'cp_proj',
    title: 'Project Management',
    description: 'Deliver complex initiatives on time, on budget, and on scope.',
    averageSalary: '₦5M – ₦20M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 15,
    recommendedSkills: ['Agile', 'Risk Management', 'Stakeholder Mgmt', 'Jira', 'Budgeting'],
    recommendedCertifications: ['PMP', 'PRINCE2', 'CSM'],
    icon: 'Kanban',
    color: 'from-orange-500 to-amber-600',
    openRoles: 103,
  },
  {
    id: 'cp_marketing',
    title: 'Digital Marketing',
    description: 'Drive growth through content, paid media, SEO, and brand campaigns.',
    averageSalary: '₦3M – ₦14M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 21,
    recommendedSkills: ['SEO', 'Google Ads', 'Analytics', 'Copywriting', 'Social Media'],
    recommendedCertifications: ['Google Digital Marketing', 'Meta Blueprint', 'HubSpot'],
    icon: 'Megaphone',
    color: 'from-rose-500 to-pink-600',
    openRoles: 167,
  },
  {
    id: 'cp_medicine',
    title: 'Medicine',
    description: 'Clinical practice, healthcare delivery, and medical specialisations.',
    averageSalary: '₦4M – ₦20M',
    demand: 'high',
    growthTrend: 'stable',
    growthPercent: 9,
    recommendedSkills: ['Clinical Skills', 'Patient Care', 'Diagnostics', 'Ethics', 'Research'],
    recommendedCertifications: ['MBBS', 'Residency Board', 'ACLS'],
    icon: 'Stethoscope',
    color: 'from-red-500 to-rose-600',
    openRoles: 54,
  },
  {
    id: 'cp_nursing',
    title: 'Nursing',
    description: 'Provide high-quality patient care across hospitals and clinics.',
    averageSalary: '₦2.5M – ₦10M',
    demand: 'very-high',
    growthTrend: 'growing',
    growthPercent: 18,
    recommendedSkills: ['Patient Care', 'Clinical Procedures', 'EMR', 'Communication', 'Triage'],
    recommendedCertifications: ['RN License', 'BLS', 'Specialty Nursing Cert'],
    icon: 'HeartPulse',
    color: 'from-pink-500 to-rose-600',
    openRoles: 92,
  },
  {
    id: 'cp_law',
    title: 'Law',
    description: 'Legal practice, corporate counsel, compliance, and advocacy.',
    averageSalary: '₦4M – ₦22M',
    demand: 'moderate',
    growthTrend: 'stable',
    growthPercent: 5,
    recommendedSkills: ['Legal Research', 'Contract Drafting', 'Litigation', 'Compliance', 'Negotiation'],
    recommendedCertifications: ['BL (Nigeria Law School)', 'LLM', 'CIPP'],
    icon: 'Scale',
    color: 'from-slate-600 to-slate-800',
    openRoles: 41,
  },
  {
    id: 'cp_civil',
    title: 'Civil Engineering',
    description: 'Design and deliver infrastructure that powers cities and communities.',
    averageSalary: '₦3.5M – ₦16M',
    demand: 'moderate',
    growthTrend: 'growing',
    growthPercent: 12,
    recommendedSkills: ['AutoCAD', 'Structural Analysis', 'Project Mgmt', 'Site Supervision', 'BIM'],
    recommendedCertifications: ['COREN', 'PMP', 'AutoCAD Professional'],
    icon: 'HardHat',
    color: 'from-stone-500 to-amber-700',
    openRoles: 67,
  },
  {
    id: 'cp_arch',
    title: 'Architecture',
    description: 'Shape the built environment through design, planning, and sustainability.',
    averageSalary: '₦3M – ₦15M',
    demand: 'moderate',
    growthTrend: 'stable',
    growthPercent: 7,
    recommendedSkills: ['Revit', 'SketchUp', 'Design Thinking', 'Sustainability', 'Presentation'],
    recommendedCertifications: ['ARCON', 'LEED GA', 'Revit Professional'],
    icon: 'Building',
    color: 'from-neutral-500 to-stone-600',
    openRoles: 38,
  },
  {
    id: 'cp_teaching',
    title: 'Teaching',
    description: 'Educate and inspire the next generation across schools and platforms.',
    averageSalary: '₦1.8M – ₦8M',
    demand: 'high',
    growthTrend: 'stable',
    growthPercent: 6,
    recommendedSkills: ['Curriculum Design', 'Classroom Mgmt', 'EdTech', 'Assessment', 'Communication'],
    recommendedCertifications: ['TRCN', 'PGDE', 'TESOL'],
    icon: 'GraduationCap',
    color: 'from-violet-500 to-indigo-600',
    openRoles: 145,
  },
  {
    id: 'cp_agri',
    title: 'Agriculture',
    description: 'Modern farming, agribusiness, and food-system innovation.',
    averageSalary: '₦2.5M – ₦12M',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 20,
    recommendedSkills: ['Agronomy', 'Supply Chain', 'Agribusiness', 'Climate Smart', 'Data'],
    recommendedCertifications: ['IITA Training', 'Organic Farming Cert'],
    icon: 'Wheat',
    color: 'from-lime-500 to-green-600',
    openRoles: 59,
  },
  {
    id: 'cp_entrepreneur',
    title: 'Entrepreneurship',
    description: 'Build startups, social ventures, and scalable businesses from zero.',
    averageSalary: 'Variable',
    demand: 'high',
    growthTrend: 'growing',
    growthPercent: 25,
    recommendedSkills: ['Fundraising', 'Product', 'Sales', 'Finance', 'Leadership'],
    recommendedCertifications: ['YC Startup School', 'Tony Elumelu Programme'],
    icon: 'Rocket',
    color: 'from-amber-500 to-yellow-600',
    openRoles: 210,
  },
];

export const FEATURED_EMPLOYERS: FeaturedEmployer[] = [
  // Technology
  { id: 'emp_google', name: 'Google', industry: 'Technology', industryGroup: 'Technology', logoPlaceholder: 'G', openRoles: 24, location: 'Lagos / Remote', description: 'Build products that help people across Africa and the world.', tags: ['Tech', 'Global'], featured: true },
  { id: 'emp_msft', name: 'Microsoft', industry: 'Technology', industryGroup: 'Technology', logoPlaceholder: 'MS', openRoles: 18, location: 'Lagos', description: 'Cloud, AI, and developer tools powering African enterprises.', tags: ['Cloud', 'AI'], featured: true },
  { id: 'emp_monie', name: 'Moniepoint', industry: 'FinTech', industryGroup: 'Technology', logoPlaceholder: 'MP', openRoles: 32, location: 'Lagos', description: 'Financial infrastructure for millions of Nigerian businesses.', tags: ['FinTech', 'Growth'], featured: true },
  { id: 'emp_paystack', name: 'Paystack', industry: 'FinTech', industryGroup: 'Technology', logoPlaceholder: 'PS', openRoles: 15, location: 'Lagos / Remote', description: "Africa's most trusted payments infrastructure.", tags: ['Payments', 'API'], featured: true },
  { id: 'emp_fw', name: 'Flutterwave', industry: 'FinTech', industryGroup: 'Technology', logoPlaceholder: 'FW', openRoles: 21, location: 'Lagos', description: 'Borderless payments for African businesses.', tags: ['Payments', 'Africa'], featured: true },
  { id: 'emp_isw', name: 'Interswitch', industry: 'FinTech', industryGroup: 'Technology', logoPlaceholder: 'IS', openRoles: 12, location: 'Lagos', description: 'Digital payments and commerce infrastructure.', tags: ['Payments', 'Enterprise'] },
  { id: 'emp_andela', name: 'Andela', industry: 'Technology', industryGroup: 'Technology', logoPlaceholder: 'AN', openRoles: 28, location: 'Lagos / Remote', description: 'Connect world-class African talent with global companies.', tags: ['Talent', 'Remote'], featured: true },
  // Banking
  { id: 'emp_gtco', name: 'GTCO', industry: 'Banking', industryGroup: 'Banking', logoPlaceholder: 'GT', openRoles: 45, location: 'Lagos', description: "Nigeria's leading retail and commercial bank.", tags: ['Banking', 'Graduate'], featured: true },
  { id: 'emp_access', name: 'Access Bank', industry: 'Banking', industryGroup: 'Banking', logoPlaceholder: 'AB', openRoles: 38, location: 'Lagos / Abuja', description: 'Pan-African banking with digital-first products.', tags: ['Banking', 'Digital'] },
  { id: 'emp_uba', name: 'UBA', industry: 'Banking', industryGroup: 'Banking', logoPlaceholder: 'UB', openRoles: 29, location: 'Lagos', description: 'Africa’s global bank with presence across the continent.', tags: ['Banking', 'Africa'] },
  { id: 'emp_zenith', name: 'Zenith Bank', industry: 'Banking', industryGroup: 'Banking', logoPlaceholder: 'ZB', openRoles: 33, location: 'Lagos', description: 'Premium banking services and corporate finance.', tags: ['Banking', 'Corporate'] },
  { id: 'emp_first', name: 'First Bank', industry: 'Banking', industryGroup: 'Banking', logoPlaceholder: 'FB', openRoles: 41, location: 'Lagos', description: "Nigeria's oldest and most iconic banking institution.", tags: ['Banking', 'Legacy'] },
  // Healthcare
  { id: 'emp_reliance', name: 'Reliance Health', industry: 'Healthcare', industryGroup: 'Healthcare', logoPlaceholder: 'RH', openRoles: 14, location: 'Lagos', description: 'Tech-enabled health insurance for Africans.', tags: ['HealthTech', 'Insurance'], featured: true },
  { id: 'emp_54gene', name: '54gene', industry: 'Healthcare', industryGroup: 'Healthcare', logoPlaceholder: '54', openRoles: 6, location: 'Lagos', description: 'Genomics and precision medicine for African populations.', tags: ['Genomics', 'Research'] },
  // Education
  { id: 'emp_alt', name: 'AltSchool Africa', industry: 'Education', industryGroup: 'Education', logoPlaceholder: 'AS', openRoles: 9, location: 'Lagos / Remote', description: 'World-class software engineering education for Africa.', tags: ['EdTech', 'Engineering'], featured: true },
  { id: 'emp_semi', name: 'Semicolon', industry: 'Education', industryGroup: 'Education', logoPlaceholder: 'SC', openRoles: 7, location: 'Lagos', description: 'Training Africa’s next generation of software engineers.', tags: ['EdTech', 'Training'] },
  // Government
  { id: 'emp_nitda', name: 'NITDA', industry: 'Government', industryGroup: 'Government', logoPlaceholder: 'NT', openRoles: 11, location: 'Abuja', description: 'Driving digital economy policy and innovation in Nigeria.', tags: ['GovTech', 'Policy'] },
  { id: 'emp_ncc', name: 'NCC', industry: 'Government', industryGroup: 'Government', logoPlaceholder: 'NC', openRoles: 8, location: 'Abuja', description: 'Regulating and advancing Nigeria’s communications sector.', tags: ['Telecom', 'Policy'] },
  { id: 'emp_cbn', name: 'CBN', industry: 'Government', industryGroup: 'Government', logoPlaceholder: 'CB', openRoles: 16, location: 'Abuja', description: "Nigeria's central bank and monetary authority.", tags: ['Finance', 'Policy'], featured: true },
  // Media
  { id: 'emp_channels', name: 'Channels TV', industry: 'Media', industryGroup: 'Media', logoPlaceholder: 'CT', openRoles: 10, location: 'Lagos', description: "Nigeria's leading independent television news network.", tags: ['Media', 'News'] },
  { id: 'emp_bd', name: 'BusinessDay', industry: 'Media', industryGroup: 'Media', logoPlaceholder: 'BD', openRoles: 5, location: 'Lagos', description: 'Premier business and financial news for decision-makers.', tags: ['Media', 'Business'] },
  // NGOs
  { id: 'emp_tef', name: 'Tony Elumelu Foundation', industry: 'NGO', industryGroup: 'NGOs', logoPlaceholder: 'TE', openRoles: 8, location: 'Lagos / Africa', description: 'Empowering African entrepreneurs with capital and mentoring.', tags: ['Impact', 'Entrepreneurship'], featured: true },
  { id: 'emp_unicef', name: 'UNICEF', industry: 'NGO', industryGroup: 'NGOs', logoPlaceholder: 'UN', openRoles: 13, location: 'Abuja / Global', description: 'Protecting the rights and wellbeing of every child.', tags: ['UN', 'Impact'], featured: true },
  { id: 'emp_undp', name: 'UNDP', industry: 'NGO', industryGroup: 'NGOs', logoPlaceholder: 'UD', openRoles: 9, location: 'Abuja / Global', description: 'Sustainable development and poverty eradication programmes.', tags: ['UN', 'Development'] },
];

export const WEEKLY_INSIGHTS: WeeklyInsights = {
  weekLabel: 'Jul 14 – Jul 20, 2026',
  mostInDemandSkills: [
    { skill: 'Python', demandScore: 94, changePercent: 12 },
    { skill: 'React', demandScore: 91, changePercent: 8 },
    { skill: 'SQL', demandScore: 88, changePercent: 5 },
    { skill: 'Cloud (AWS)', demandScore: 86, changePercent: 15 },
    { skill: 'Data Analysis', demandScore: 82, changePercent: 10 },
    { skill: 'Cybersecurity', demandScore: 79, changePercent: 18 },
    { skill: 'Product Management', demandScore: 74, changePercent: 7 },
    { skill: 'UI/UX Design', demandScore: 71, changePercent: 6 },
  ],
  fastestGrowingIndustries: [
    { industry: 'Artificial Intelligence', growthPercent: 48, openings: 98 },
    { industry: 'FinTech', growthPercent: 31, openings: 312 },
    { industry: 'Cybersecurity', growthPercent: 41, openings: 74 },
    { industry: 'HealthTech', growthPercent: 27, openings: 86 },
    { industry: 'Agritech', growthPercent: 22, openings: 59 },
    { industry: 'EdTech', growthPercent: 19, openings: 67 },
  ],
  mostActiveStates: [
    { state: 'Lagos', openings: 1240, changePercent: 14 },
    { state: 'Abuja FCT', openings: 486, changePercent: 11 },
    { state: 'Rivers', openings: 178, changePercent: 6 },
    { state: 'Oyo', openings: 142, changePercent: 9 },
    { state: 'Kano', openings: 98, changePercent: 4 },
    { state: 'Enugu', openings: 76, changePercent: 8 },
  ],
  averageSalaries: [
    { role: 'Software Engineer', averageSalary: '₦12M', range: '₦6M – ₦25M' },
    { role: 'Data Analyst', averageSalary: '₦7.5M', range: '₦4M – ₦15M' },
    { role: 'Product Manager', averageSalary: '₦14M', range: '₦7M – ₦24M' },
    { role: 'UX Designer', averageSalary: '₦8M', range: '₦4M – ₦18M' },
    { role: 'DevOps Engineer', averageSalary: '₦15M', range: '₦8M – ₦26M' },
  ],
  trendingOpportunities: [
    { title: 'Backend Engineering Intern', organization: 'Paystack', type: 'Internship', views: 4820 },
    { title: 'Google Africa Developer Scholarship', organization: 'Google', type: 'Scholarship', views: 3910 },
    { title: '3MTT Fellowship', organization: '3MTT Nigeria', type: 'Fellowship', views: 3540 },
    { title: 'Junior Data Analyst', organization: 'Flutterwave', type: 'Job', views: 2890 },
  ],
  upcomingDeadlines: [
    { title: 'Junior Data Analyst', organization: 'Flutterwave', deadline: '2026-08-05', daysLeft: 20 },
    { title: 'Digital Marketing Specialist', organization: 'Jumia', deadline: '2026-08-08', daysLeft: 23 },
    { title: 'NYSC Tech Placement', organization: 'Andela', deadline: '2026-08-10', daysLeft: 25 },
    { title: 'Business Analyst', organization: 'Access Bank', deadline: '2026-08-11', daysLeft: 26 },
  ],
  communityEvents: [
    { id: 'ev_1', title: 'Naija Tech Community AMA', date: '2026-07-18', location: 'Online', type: 'webinar', attendees: 320 },
    { id: 'ev_2', title: 'Women in Tech Lagos Meetup', date: '2026-07-19', location: 'Yaba, Lagos', type: 'meetup', attendees: 85 },
    { id: 'ev_3', title: 'Career Switch Workshop', date: '2026-07-20', location: 'Abuja', type: 'workshop', attendees: 60 },
  ],
  techMeetups: [
    { id: 'tm_1', title: 'LagosJS Monthly Meetup', date: '2026-07-17', location: 'Andela EPIC Tower', type: 'meetup', attendees: 140 },
    { id: 'tm_2', title: 'Python Nigeria Hangout', date: '2026-07-19', location: 'Online', type: 'meetup', attendees: 210 },
    { id: 'tm_3', title: 'DevOps Nigeria Circle', date: '2026-07-21', location: 'Victoria Island', type: 'meetup', attendees: 55 },
  ],
  careerFairs: [
    { id: 'cf_1', title: 'Lagos Tech Career Fair 2026', date: '2026-07-25', location: 'Eko Hotel, Lagos', type: 'career-fair', attendees: 2500 },
    { id: 'cf_2', title: 'Abuja Graduate Job Fair', date: '2026-07-28', location: 'Transcorp Hilton', type: 'career-fair', attendees: 1200 },
    { id: 'cf_3', title: 'Virtual Africa Talent Fair', date: '2026-08-02', location: 'Online', type: 'career-fair', attendees: 5000 },
  ],
};

export const FILTER_OPTIONS = {
  industries: [
    'all',
    'Technology',
    'Banking & FinTech',
    'Healthcare',
    'Education',
    'Agriculture',
    'Energy',
    'Logistics',
    'Government',
    'Legal',
    'Media',
    'Retail',
    'Construction',
    'Manufacturing',
    'Aviation',
    'Hospitality',
    'Sales & Marketing',
    'Business & Consulting',
    'Creative & Design',
    'Research',
    'Non-Profit',
  ],
  jobTypes: ['all', 'full-time', 'part-time', 'contract', 'internship', 'freelance'] as const,
  workModes: ['all', 'remote', 'hybrid', 'onsite'] as const,
  locations: ['all', 'Lagos', 'Abuja', 'Port Harcourt', 'Ibadan', 'Kano', 'Enugu', 'Remote', 'International'],
  states: [
    'all',
    'Lagos',
    'Abuja FCT',
    'Rivers',
    'Kano',
    'Kaduna',
    'Enugu',
    'Oyo',
    'Ogun',
    'Delta',
    'Anambra',
    'Edo',
  ],
  salaryRanges: ['all', '0-5M', '5M-15M', '15M-30M', '30M+'],
  experienceLevels: ['all', 'entry', 'mid', 'senior', 'executive'] as const,
  educationLevels: ['all', 'secondary', 'diploma', 'bachelors', 'masters', 'phd', 'any'] as const,
  companySizes: ['all', 'startup', 'sme', 'mid', 'enterprise'] as const,
  categories: [
    'all',
    'job',
    'scholarship',
    'fellowship',
    'internship',
    'hackathon',
    'learning',
    'competition',
    'networking',
    'volunteer',
  ],
  opportunityTypes: [
    'all',
    'job',
    'scholarship',
    'fellowship',
    'internship',
    'hackathon',
    'learning',
    'volunteer',
  ],
  deadlines: ['all', 'week', 'month', '3months'],
  countries: ['all', 'Nigeria', 'Ghana', 'Kenya', 'South Africa', 'Global'],
  sectorTypes: ['all', 'government', 'private', 'startup', 'ngo', 'international'] as const,
  costTypes: ['all', 'free', 'paid'] as const,
};
